version: '3.3'

services:
  db:
    image: mariadb:10.9
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env
    environment:
      TZ: Asia/Seoul
    restart: always
  cicd:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: "always"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8080:8080"
    privileged: true
    user: root